fix: corrigindo erro de datas iguais no filtro de rankings ab#0001
gustavosilva7/bibliotech-react pull request #1
Opened 2024-01-03 19:14 UTC by pedroluanx28

-Adicionei um estado que armazena se a tabela deve ser a filtrada ou a normal, assim conseguindo utilizar a função tabela para os dois casos (eu apaguei a função filteredTable).
-tive alguns desafios nessa task, o código as vezes me deixava tonto.

2024-01-03 19:25 UTC, gustavosilva7 requested changes
mude a logico completa

2024-01-04 16:29 UTC, gustavosilva7 requested changes
ainda existe um erro na logica ao passar determinadas datas

2024-01-04 16:31 UTC, gustavosilva7 commented
exemplo: dia 02 ate dia 03 so mostra 1 resultado, dia 3 para dia 3 mostra 3

2024-01-04 16:49 UTC, pedroluanx28 commented
LGTM

2024-01-04 16:59 UTC, gustavosilva7 requested changes
adicione algo para simbolizar quando não ha nenhum dado apos a filtragem

2024-01-04 17:19 UTC, gustavosilva7 approved these changes
.

2024-01-04 17:19 UTC, merged